### ISSUE TITLE
adding new field

### ISSUE THREAD

**Issue by beshad** [phoinixi/jsonresume-theme-stackoverflow#34]
hi,
thank you for this fantastic theme. i am using it for my resume. i do have one inquiry. i am trying to add one field (summary) to Skills. i have modified the `resume.json` file in the root of project and then tried to add the summary field to the handlebar template file in themes/partials/skills.hbs but it doesn't work. the field is unknown to skills.hbs. do i need to change the core code anywhere else to add new fields where i want it? i use this theme via 'HackMyResume'. 
cheers for the help

**Comment by francescoes** [comment]
Hi Beshad, 

Can you post an example of your code?
