### ISSUE TITLE
Should be used image and not picture

### ISSUE THREAD

**Issue by lfbn** [phoinixi/jsonresume-theme-stackoverflow#36]
Hi,

According to the [JSON schema](https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json) is image. Shouldn't this be changed from picture?
https://github.com/phoinixi/jsonresume-theme-stackoverflow/blob/43adedfc4ad980a5b7a314412a4a32f6568eae7a/theme/partials/basics.hbs#L3

Thanks.

**Comment by phoinixi** [comment]
Nice catch, do you want to contribute and fix it or are you asking for a bug fix?

**Comment by lfbn** [comment]
I will contribute. Thanks.

**Comment by lfbn** [comment]
Here it is PR #37 .

**Comment by phoinixi** [comment]
Thanks for contributing
