### ISSUE TITLE
Section overflow

### ISSUE THREAD

**Issue by waldoibarra** [phoinixi/jsonresume-theme-stackoverflow#43]
When the previous section content overflows, it makes the next section header go to the right.

Here is an example of issue.

![image](https://user-images.githubusercontent.com/10247456/66709784-f704a280-ed30-11e9-9043-d1bb67b031b9.png)

A possible fix could be to update the `margin-bottom` on the [`.section`](https://github.com/phoinixi/jsonresume-theme-stackoverflow/blob/master/style.css#L203) class to be `2rem`, not creating a PR since I'd like to hear someone's opinion on this as this feels like a hack instead of a fix.

**Comment by kpennell** [comment]
Agree to this. This definitely breaks up an otherwise amazing theme. @phoinixi thoughts?

**Comment by phoinixi** [comment]
I didn't notice this, in the next weeks I will fix all the bugs

**Comment by LuD1161** [comment]
@phoinixi any update on this 🤔
