### ISSUE TITLE
Update npm package to the latest version

### ISSUE THREAD

**Issue by michaltalaga** [phoinixi/jsonresume-theme-stackoverflow#44]
there have been schema changes in json resume. namely work.company -> work.name

this is already implemented in work.hbs in github but not published to npmjs

**Comment by phoinixi** [comment]
yes, I should do that or find a different solution

**Comment by clementdevos** [comment]
Hey, we'd very much like you to publish the a new version of this theme, for the same reasons as @michaltalaga

**Comment by frg** [comment]
For the moment I've been referencing the master branch directly until this is resolved

**Comment by phoinixi** [comment]
fixed and updated everything with last release
