### ISSUE TITLE
Float right on dates pdf vs. html

### ISSUE THREAD

**Issue by kpennell** [phoinixi/jsonresume-theme-stackoverflow#48]
Hey there @phoinixi . I love this and have tried to tweak it for my needs.

Anyway, I have an odd problem where the dates pull right on html but not PDF
html
![image](https://user-images.githubusercontent.com/1060385/72029359-8a6b4800-323a-11ea-81c3-396e54c1b632.png)

pdf version

![image](https://user-images.githubusercontent.com/1060385/72029378-9951fa80-323a-11ea-8e56-22280a2d0cbf.png)

Any suggestions?

**Comment by phoinixi** [comment]
I am replying very late to this but it's fixed now
