### ISSUE TITLE
Theme not rendering CSS on official registry

### ISSUE THREAD

**Issue by thomasdavis** [phoinixi/jsonresume-theme-stackoverflow#52]
Hey mate, love this theme. 

I am trying to debug why this is currently not rendering on the official them server -> https://themes.jsonresume.org/theme/stackoverflow

Looks like the style tag is coming out empty. 

It is deploying `"jsonresume-theme-stackoverflow": "^1.4.0"`

I will keep investigating.

**Comment by phoinixi** [comment]
Hey, sorry for the extremely late reply, I just checked and it seems to be rendering CSS now, will close this
