### ISSUE TITLE
Question: Where to find the level strings for skills and language

### ISSUE THREAD

**Issue by sgofferj** [phoinixi/jsonresume-theme-stackoverflow#53]
I'm searching for the level strings for skills and language but I can't seem to find them. I mean like "Fluent", "Intermediate", "Master", etc. Could somebody please point me to the right direction?

**Comment by LuD1161** [comment]
@sgofferj it's in the css file [here](https://github.com/phoinixi/jsonresume-theme-stackoverflow/blob/master/style.css#L546)
![image](https://user-images.githubusercontent.com/17861054/97580835-d5e52180-1a19-11eb-92ec-ba5078ed3620.png)
```
Beginner
Intermediate
Advanced
Master
```

**Comment by sgofferj** [comment]
@LuD1161 Thanks!
