### ISSUE TITLE
This fork fixes some of the issues of this project -https://github.com/phnx47/jsonresume-theme-stackoverflow-phnx47

### ISSUE THREAD

**Issue by kpennell** [phoinixi/jsonresume-theme-stackoverflow#58]
I really appreciate this theme but it needs several fixes. This fork implements several https://github.com/phnx47/jsonresume-theme-stackoverflow-phnx47

hope it helps others

**Comment by phoinixi** [comment]
Can open a PR or open specific issue, this item is too generic, I will close it
