### ISSUE TITLE
Icon for Keybase

### ISSUE THREAD

**Issue by v6** [phoinixi/jsonresume-theme-stackoverflow#59]
Would you please add the ability to generate an icon for KeyBase?

**Comment by v6** [comment]
I guess it would go on the list here: https://www.npmjs.com/package/jsonresume-theme-stackoverflow#social-profiles-icons

**Comment by dwysocki** [comment]
Looks like KeyBase is actually one of the supported icons.  See #61.

**Comment by phoinixi** [comment]
supported already as pointed out by @dwysocki. Please use `keybase` as network name and you will see the icon
