### ISSUE TITLE
More complete list of supported networks

### ISSUE THREAD

**Issue by dwysocki** [phoinixi/jsonresume-theme-stackoverflow#61]
The Readme lists a few supported social networks for including icons.  It appears, however, to be incomplete, as the true list is anything in [FontAwesome](https://use.fontawesome.com/releases/v5.0.12/css/all.css) which gets loaded in `resume.hbs`.

Obviously you don't want to list every network in FontAwesome, but it might be helpful to link to that CSS file (messy) or better yet, if there's a user-friendly webpage that describes what's in the CSS file, link to that.

**Comment by phoinixi** [comment]
thanks, I updated the docs
