### ISSUE TITLE
Support "certificates"

### ISSUE THREAD

**Issue by hukacode** [phoinixi/jsonresume-theme-stackoverflow#63]
Hello,

Could you please consider adding the "certificates" section?

**Comment by phoinixi** [comment]
Hi, I am going to fix bugs on this project and create a new one in React, so no new features, sorry. But I will definitely consider that  for the new project, altough you can use the 'award' section for now

**Comment by levino** [comment]
Hey @phoinixi I [migrated it all to react](https://github.com/levino/jsonresume-theme-stackoverflow), maybe you wanna take a look? You can also merge it, if you want. I also fixed some bugs (usage of non schema conform keys etc.) and will now polish out what I broke during the migration. I also have storybook in place and will add i18n support for the headings of the output too (that is why I started this in the beginning).
