### ISSUE TITLE
Location object not supported in work

### ISSUE THREAD

**Issue by sgofferj** [phoinixi/jsonresume-theme-stackoverflow#71]
Volunteer and Education support a location object but Work does not. When adding a location object to a work object, it's displayed as `[object Object]`.

**Comment by millette** [comment]
@sgofferj How is your location formatted? Can you give a sample? Mine is a string and works as expected.

**Comment by sgofferj** [comment]
@millette 
I meant a JSON object like
```json
"location": {
    "city": "Valkeakoski",
    "countryCode": "FI",
    "region": "Finland"
}
```

That works in the volunteer and the education section but not in the work experiences.

**Comment by cskwrd** [comment]
The theme is following the [schema](https://github.com/jsonresume/resume-schema/blob/8a5b3982f8e5b9f8840398e162a6e0c418d023da/schema.json#L111-L113) with respect to work location.

**Comment by phoinixi** [comment]
I see your confusion @sgofferj but the location is a string for the work object according to the JSON schema. This won't be changedf
