### ISSUE TITLE
Which package manager is used in this project?

### ISSUE THREAD

**Issue by cskwrd** [phoinixi/jsonresume-theme-stackoverflow#72]
The repo has both a `package-lock.json` file and a `yarn.lock` file.

If I run `yarn install`, there is a warning about the existence of a `package-lock.json` file and it is unwise to use multiple package managers.

If I run `npm install`, the packages are installed without issue, but nearly every line in the `yarn.lock` file is touched. It appears that the changes are just re-ordering the information about each package. Is that okay? Is `npm` the package manager I should be using?

**Comment by phoinixi** [comment]
use npm, yarn.lock deleted
