### ISSUE TITLE
"tags" are full width now

### ISSUE THREAD

**Issue by levino** [phoinixi/jsonresume-theme-stackoverflow#75]
I think https://github.com/phoinixi/jsonresume-theme-stackoverflow/commit/b413bed58bc2c3c8f15da6599617ae365e9008db#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7aR376 was a mistake. This is how it used to look:
![Screenshot 2023-04-27 at 11 02 51](https://user-images.githubusercontent.com/1150767/234814330-8ac64a71-502f-4f1d-bfbc-4a742054e597.png)
This is how it looks now:
![Screenshot 2023-04-27 at 11 03 10](https://user-images.githubusercontent.com/1150767/234814373-617bd79b-438f-49e3-bcea-dfdf47fec720.png)

**Comment by phoinixi** [comment]
would you like to create a PR for this fix ?🔥

**Comment by levino** [comment]
I kinda did :) https://github.com/phoinixi/jsonresume-theme-stackoverflow/issues/63#issuecomment-1527373698
