### ISSUE TITLE
Merge levinos updates / upgrades

### ISSUE THREAD

**Issue by levino** [phoinixi/jsonresume-theme-stackoverflow#80]
Hi there, this is an issue to discuss whether you want to merge my changes. I have created a fork and released a new [package](https://www.npmjs.com/package/jsonresume-theme-stackoverflow-react). Please also see the [demo repo](https://github.com/levino/demo-for-react-jsonresume-theme) for how to use it.

It has the following advantages:
- Based on `react` and `jsx`
- `storybook` enabled
- Support for translation / multilanguage

Happy to discuss.

**Comment by phoinixi** [comment]
Hey @levino that is great, I wish you brought it up before writing the code. I am working on the same thing, but my idea is a bit different, I had a look at your code and you really put a lot of effort into it. I like the idea, but I will tell you why I am not merging it at this time and also present you my idea and how it differs from yours:

- I would keep the Rect CV from the original separated to let people still use the old one, I guess it's still valuable
- The React version I would like to be a base to write any template, not only Stackoverflow style, as soon as I have a first version I will publish it on my GitHub profile

**Comment by levino** [comment]
Do not worry @phoinixi With ChatGPT helping me, it was actually okay. And I needed to have a German CV right now and not in some distant future. So even if my changes are never merged, that is okay.

Also feel free to just take part of my code (for example the `.tsx` files with the translated components). I guess you will need them anyhow. Also for me it was very important to have the multilanguage feature available. I already thought you might not be interested in this additional complexity so that is also fine.

On the matter of a base for "any" template, I think it is not necessary to have a react template set up but rather provide the building blocks for that, which are:
- An example cv using all available keys of the schema (an only these! Your code actually supports some keys I could not find in the json schema!)
- Some nice and easy higher order function that takes a react component and returns the `pdfRenderOptions` and the `render` function for `resume-cli`
- Maybe some general stuff like proper TypeScript config, build scripts etc.
All of this stuff is in my repo and I invite you to take what you can use from there. Maybe just clone it and throw everything out, that you do not like. Could also be an idea to switch from static css to something like `styled-components` or `tailwind-css` but I think that would already be too opinionated for a template / boilerplate theme.

**Comment by phoinixi** [comment]
> Some nice and easy higher order function that takes a react component and returns the pdfRenderOptions and the render function for resume-cli

this is the crucial part, your template is valid, I am currently work on this

**Comment by levino** [comment]
Hey @phoinixi, nice to see some activity here. Could you explain which changes made you close this issue? Or is this a wontfix?

Since you seemed inactive for a while, I took the liberty to [merge my fork](https://github.com/jsonresume/jsonresume.org/issues/17) of your project into the jsonresume monorepo. So there now is @jsonresume/theme-stackoverflow and jsonresume-theme-stackoverflow. I think this should be adressed and one of them should be deprecated. Everything else will just be painful.
